### ISSUE TITLE
Exception when selecting Log in Load Dataset dialog

### ISSUE THREAD

**Issue by StephenNneji** [mantidproject/mantidimaging#1001]
### Summary

I encounter an exception when attempting to select the "Flat Before Log" or "Flat After Log" in the Load Dataset dialog

### Steps To Reproduce

- Click File > Load dataset
- Click the "Flat Before Log" or "Flat After Log" select button in the dialog

### Expected Behaviour

The software should either allow user to select the logs or give useful error message

### Current Behaviour

The software throws the exception shown in the screenshot below 

### Context

This error occurred in version 2.1 installed on IDAaas

### Failure Logs

see screenshot

### Screenshot(s)

![Screenshot 2021-05-28 092102](https://user-images.githubusercontent.com/34302892/120001275-870d6380-bfcb-11eb-87ec-37113e77937f.png)

**Comment by samtygier-stfc** [comment]
I can confirm this is still an issue on master

```
2021-05-28 17:05:28,882 [mantidimaging.gui.windows.main.view:L365] ERROR: Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/load_dialog/view.py", line 75, in <lambda>
    self.select_flat_before_log.clicked.connect(lambda: self.presenter.notify(
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/load_dialog/presenter.py", line 46, in notify
    self.do_update_single_file(**baggage)
TypeError: do_update_single_file() got an unexpected keyword argument 'image_file'

```
