### ISSUE TITLE
Investigate test_not_executed tests in operations

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1162]
### Summary

Several operations have tests with names containing `test_not_executed`.

In `ring_removal_test` the operation is called with `run_ring_removal`. This should be removed #1161

In `rebin_test` the test check that operation does nothing when some of the inputs are invalid. This case would probably be better handled by raising a `ValueError`

In `gaussian_test` it check that the data *is* modified. Again this should raise an error.

```
mantidimaging/core/operations/gaussian/test/gaussian_test.py
28:    def test_not_executed(self):

mantidimaging/core/operations/rebin/test/rebin_test.py
23:    def test_not_executed_rebin_negative(self):
33:    def test_not_executed_rebin_zero(self):

mantidimaging/core/operations/median_filter/test/median_filter_test.py
26:    def test_not_executed(self):

mantidimaging/core/operations/roi_normalisation/test/roi_normalisation_test.py
25:    def test_not_executed_empty_params(self):
34:    def test_not_executed_invalid_shape(self):

mantidimaging/core/operations/ring_removal/test/ring_removal_test.py
23:    def test_not_executed(self):
```
There might be more similar tests with different names.

**Comment by rbauststfc** [comment]
For the Rebin case, changing this to raise a `ValueError` means we might want to do the following to prevent the error being encountered via the GUI:

1) Change the min values for the "Rebin for Dimensions" spin boxes to be 1 and the "Rebin by Factor" spin box to be 0.01. At the moment both are 0, allowing the user to enter an invalid value.

2) Set a default value for "Rebin for Dimensions" (a default value is already provided for "Rebin by Factor"). In testing I've noticed that a smaller default (i.e. 1 x 1) can cause a slight delay when selecting the "Rebin for Dimensions" checkbox, which may not be desirable. @samtygier-stfc do you know what a sensible default size for this field would be, or do we need to check with the users?
