### ISSUE TITLE
Dataset Tree View: Allow adding 180 after dataset has been loaded

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [mantidproject/mantidimaging#1189]
### Desired Behaviour

The tree view should get updated when a 180 file is added to a dataset that previously didn't have one.

**Comment by samtygier-stfc** [comment]
Once this is implemented then the TestGuiSystemLoading.test_load_180 test can be fixed and the xfail removed, see 1b3cbdab293be9c78b09239873f28deef2cc9583

**Comment by DolicaAkelloEgwel** [comment]
Fixed in #1258
