### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1235]
### Operations window

Remove outliers
Difference should have a range 0 - 10,000

ROI Normalisation
Normalisation mode: default should be Stack Average

Clip
All boxes, step size should be 0.1

Ring removal
Threshold, Threshold Min, Threshold Max, step size should be 0.1

Stripe filters
All the float / QDoubleSpinBox inputs.

Note:
For the step size changes, `add_property_to_form()` does not have a way to set this. `ArithmeticFilter` shows how to set it with `setSingleStep`.  I think it makes sense for `add_property_to_form()` to default to 0.1 step size for any float input not set manually.

### Recon window
Beam hardening correction
Show 4 decimal places, stepsize 0.01

**Comment by rbauststfc** [comment]
I've noticed that if you click either of the dividers from the filter drop-down in the Operations window the intended behaviour is that the system will render the fields for the first menu option below the divider. The system does do this, however you also get a series of windows popping up, one for each of the fields in the layout that was rendered.

In the `handle_filter_selection` method we have the following code:

```
        if filter_name == self.presenter.divider:
            self.filterSelector.setCurrentIndex(self.filterSelector.currentIndex() + 1)
```

What seems to happen is that the call to change the index here triggers another call to the `handle_filter_selection` method. When that completes, we pick up where we left off from the original call (the one triggered by selecting the divider), resulting in the pop-ups. Adding a `return` to this `if` statement solves the problem by terminating the original call. @samtygier-stfc, as this is a small fix, I assume it would be worth including along with the rest of this work?
