### ISSUE TITLE
Wizard does not notice load step done

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1301]
### Summary

The wizard should enable pre-processing steps once a dataset is loaded

### Steps To Reproduce

Open wizard
Click Loading files and Run
Select files in Load dialog, click ok

### Expected Behaviour

Next steps should become enabled once load is complete

### Current Behaviour

Loaded stacks are not detected

### Context

Main. Probably due to how the wizard looks for open stacks needing updating for datasets.

**Comment by rbauststfc** [comment]
When I was testing I found that if you load a second dataset through the wizard then it seems to enable the next steps. It's just loading the first dataset that doesn't seem to be picked up.
