### ISSUE TITLE
Initial ROI box is sometimes much larger than image

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [mantidproject/mantidimaging#1330]
### Desired Behaviour

Starting box is the same size as/smaller than the image.

### Current Behaviour

You sometimes get things like this and have to drag it until the bottom right corner is visible in order to resize the box: 
![image](https://user-images.githubusercontent.com/43887608/155370275-deaa747b-49a4-4920-8211-e640ad49051a.png)

**Comment by rbauststfc** [comment]
I've had a look at this to see if there is a quick fix. While I think there is one to address the ROI size being incorrect for the image (see below), I also think it would be worth spending just a little bit of time on this as I've noticed that the ROI selection dialog doesn't seem to work in tandem with the value from the input field. At the moment, when you open the dialog it uses a hard-coded value of 300 x 300, regardless of what is entered into the input field. If you open the dialog, don't change anything and then click OK it doesn't update the ROI input field, even though the size of the selected region in the dialog is different to the region entered in the field - you have to move or resize the region for the input field to update. If you have the ROI selection dialog open and you change the value in the input field then this isn't reflected in the dialog either. Unless it was a deliberate decision to have these two controls working independently, I think it would be good and should be very possible to have them working together a bit more.

For when this is picked up, at time of writing I found that method `roi_visualiser` in the `FiltersWindowView` class is the part of the code that configures and opens the ROI dialog. The dialog is used for both Crop Co-ordinates and ROI Normalisation. I experimented with adding the following code within this method, which started to address setting the initial size of the ROI:

```
        def find_roi_values():
            try:
                values = [int(value) for value in roi_field.text().strip().split(',')]
                if len(values) == 4:
                    return values
            except ValueError:
                pass
            # If we can't get valid ROI values from the input field then set to the whole image size
            return [0, 0, self.roi_view.image_data.shape[2], self.roi_view.image_data.shape[1]]

  roi_values = find_roi_values()
  self.roi_view.roi.setPos(roi_values[0], roi_values[1])
  self.roi_view.roi.setSize(roi_values[2], roi_values[3])
```

**Comment by samtygier-stfc** [comment]
Having them sync'ed properly sounds like a good improvement.
