### ISSUE TITLE
New filter GUI

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantidimaging#138]
Open the filter dialog from a single menu option and select from a drop down of different filters. This is more in line with what other packages do.

EDIT: original issue was just as above, however the GUI could do with being rewritten to follow MVP style and to better contain its functionality (half of it's logic is in `sv_presenter.py`).

Needs done before #120 

To do:
- [x] Implement new window
- [x] Update filter registration
- [x] Unit tests
- [x] Parameter passing from SV

**Comment by martyngigg** [comment]
@DanNixon Could this get annoying if you always want to pick a particular filter but you have to first open the dialog and then find the filter in the list?

Paint programs for example usual have menus with items in groups. Would that make more sense? I'm not as familiar with how users will use this so please let me know if this is a specific request.

**Comment by DanNixon** [comment]
This was a suggestion from the meeting this morning when I showed the mock-up for #120.

Tino mentioned having the filter type in this dialog would make it more like existing tools (he's going to show me a couple they use in a couple of weeks time so I can try and keep the interface consistent in the future).

**Comment by martyngigg** [comment]
:cool: Sounds fine.
