### ISSUE TITLE
ExecutionTimer unit test fails intermittently for Windows GitHub Action

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1417]
### Summary

The `ExecutionTimerTest.test_execute` unit test method is failing occasionally for the Windows GitHub Action workflow. Re-running the test eventually causes it to pass. This seems to be affecting Windows only.

### Steps To Reproduce

Requires investigation to see what is causing the failures.

### Expected Behaviour

Passes consistently

### Current Behaviour

Fails intermittently

### Context

Current main

### Failure Logs

```
self = <mantidimaging.core.utility.test.execution_timer_test.ExecutionTimerTest testMethod=test_execute>

    def test_execute(self):
        t = ExecutionTimer()
        self.assertEqual(t.total_seconds, None)
        self.assertEqual(str(t), 'Elapsed time: unknown seconds')
    
        with t:
            self.assertEqual(t.total_seconds, None)
            self.assertEqual(str(t), 'Elapsed time: unknown seconds')
    
            time.sleep(0.1)
    
>       self.assertAlmostEqual(t.total_seconds, 0.1, delta=0.05)
E       AssertionError: 0.5644240379333496 != 0.1 within 0.05 delta (0.46442403793334963 difference)

mantidimaging\core\utility\test\execution_timer_test.py:22: AssertionError
```

**Comment by samtygier-stfc** [comment]
Still seeing this 
`AssertionError: 0.2550032138824463 != 0.1 within 0.05 delta (0.15500321388244628 difference)`

Maybe we have to assume that some days the github actions runners are busy, so its not unusual for a `sleep(0.1)` to take longer than 0.1 seconds. I think this should change to assert that `t.total_seconds` is greater than 0.1.
