### ISSUE TITLE
Pytest sometimes very slow

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1427]
### Summary

The pytest step on git hub actions is usually below a minute, but sometimes is much slower, exceeding timeouts.

#1424 disabled the parallel running, so that we can see which test was being run when the timeout was reached, but this was not consistent. #1426 increases the timeouts to gather more debug information. Also I have added debug flags from https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

Some slow runs
https://github.com/mantidproject/mantidimaging/runs/6207333156?check_suite_focus=true
https://github.com/mantidproject/mantidimaging/runs/6197532458?check_suite_focus=true

Slowest tasks were 
``` 
============================ slowest 10 durations =============================
26.83s teardown mantidimaging/gui/windows/operations/test/view_test.py::OperationsWindowsViewTest::test_collapse
23.50s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_setup_stack_for_view
20.80s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_connect_histogram_changes
19.70s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_ensure_range_is_the_same_new_stack_min_original_stack_max
18.58s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_sync_roi_plot_for_new_stack_with_old_stack
17.56s call     mantidimaging/gui/windows/operations/test/view_test.py::OperationsWindowsViewTest::test_collapse
17.46s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_closeEvent
16.61s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_toggle_roi_show_true
16.37s call     mantidimaging/gui/windows/operations/test/view_test.py::OperationsWindowsViewTest::test_on_auto_update_triggered_with_auto_not_selected
15.70s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_images_are_synced
========= 871 passed, 104 skipped, 290 warnings in 471.92s (0:07:51) ==========
```
another slow one
```

============================ slowest 10 durations =============================
23.67s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_closeEvent_message_pop_up_if_choice_not_made_and_notifies_presenter_on_ok
22.73s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_sync_roi_plot_for_old_stack_with_new_stack
21.83s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_closeEvent_message_pop_up_if_choice_not_made_and_doesnt_notify_presenter_on_cancel
20.82s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_closeEvent
19.90s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_sync_timelines_for_old_stack_with_new_stack
19.01s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_sync_roi_plot_for_new_stack_with_old_stack
18.12s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_setup_stack_for_view
17.16s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_toggle_roi_show_true
16.25s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_toggle_roi_show_false
15.36s call     mantidimaging/gui/windows/stack_choice/tests/view_test.py::StackChoiceViewTest::test_ensure_range_is_the_same_new_stack_max_original_stack_min
========= 871 passed, 104 skipped, 298 warnings in 417.25s (0:06:57) ==========
```

**Comment by rbauststfc** [comment]
Update on investigations 28-29/04/2022:

1) Order of the test run doesn't seem to be relevant - using the same running order as a previously failed test run does not give consistent (or even increased) failures.

2) The `StackChoiceView` tests appear to run slowly at times, particularly when the overall test run has been slow. However, removing these tests did not prevent timeouts.

3) Most of the time the run will complete within 15 minutes, even if it takes longer than the currently specified 5 minute timeout. However, there have been a very small number of occasions where the run seems as if it will hang indefinitely (i.e. hasn't completed within a 60 minute timeout).

4) Still investigating if removing the process pool start-up from the unit tests improves things - this requires further monitoring to assess if it's making any difference.

5) I've so far not managed to replicate the issue locally.

6) I've not managed to interpret a great deal from the GitHub Actions worker diagnostic logs. A run that's working on Linux seems to output lots of sequences of this sort of thing:

> INFO JobServerQueue] Try to append 1 batches web console lines for record 'UUID', success rate: 1/1.
> INFO JobServerQueue] Try to append 1 batches web console lines for record 'UUID', success rate: 1/1.
> INFO JobServerQueue] Try to append 1 batches web console lines for record 'UUID', success rate: 1/1.
> INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.290.1/bin'
> INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.290.1'
> INFO HostContext] Well known directory 'Work': '/home/runner/work'

Whereas at the point that it's hanging we no longer see the JobServerQueue entries and see something like this:

> INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.290.1/bin'
> INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.290.1'
> INFO HostContext] Well known directory 'Work': '/home/runner/work'
> INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.290.1/bin'
> INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.290.1'
> INFO HostContext] Well known directory 'Work': '/home/runner/work'
> INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.290.1/bin'
> INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.290.1'
> INFO HostContext] Well known directory 'Work': '/home/runner/work'
> INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.290.1/bin'
> INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.290.1'
> INFO HostContext] Well known directory 'Work': '/home/runner/work'

Until the timeout is reached. I'm not sure of the significance of this, though. There are occasionally websocket errors that appear in the logs, but they seem to appear in logs for both failed and successful runs without an obvious pattern for the failed runs.

**Comment by samtygier-stfc** [comment]
With the following script I found a few test files that fail in isolation:

```bash
#!/bin/bash
TESTCOMMAND="xvfb-run --auto-servernum python -X faulthandler -m pytest  --cov --cov-report=xml -n auto --ignore=mantidimaging/eyes_tests --durations=10"

date > test_log.txt
test_files=`find mantidimaging/ | grep 'test.py$'`
for f in ${test_files}
do
        if timeout 60s ${TESTCOMMAND} ${f}
        then
                echo PASS ${f} >> test_log.txt
        else
                echo FAIL ${f} >> test_log.txt
        fi
done
cat test_log.txt

```
The failures are:
```
FAIL mantidimaging/gui/windows/welcome_screen/tests/presenter_test.py
FAIL mantidimaging/core/gpu/test/gpu_test.py
FAIL mantidimaging/core/operations/rebin/test/rebin_test.py
FAIL mantidimaging/core/operations/median_filter/test/median_filter_test.py
```
I think in sequential mode (wihtout `-n auto`) all the test files get imported before any code is run. In parallel mode new processes (or threads?) are started with a subset of test files, so there can be differences in global state.

welcome_screen/tests/presenter_test.py #1446

**Comment by rbauststfc** [comment]
> I managed to reproduce locally on linux if I use the full command from that is used on github actions. I wonder if its an interaction between MI's multiprocessing, pytest-xdist and pytest-cov. Some experiments on #1445 but I don't see a pattern yet.

That could help a lot if we can reproduce locally. Doing some reading around, I've not found anything that exactly matches our situation, but there do seem to be various reports of issues with pytest + multiprocessing hanging, and pytest-xdist and pytest-cov were mentioned in a few things I read. Perhaps a good first step would be to try updating our pytest versions to the latest releases?

**Comment by rbauststfc** [comment]
I've been running some tests locally using this command (which is our full GitHub Actions command plus a seed that seems to fail fairly regularly on Linux):

`xvfb-run --auto-servernum python -m pytest --cov --cov-report=xml -n auto --ignore=mantidimaging/eyes_tests --durations=10 --randomly-seed=2998623717`

I've opened a PR to update pytest and coverage versions so we can monitor and see if any time outs appear after a while. I've included further details on that PR of some small additional things I found when testing and some information I found when trying to research the problem.

**Comment by samtygier-stfc** [comment]
I've not seen timeouts for pytest in a while now, so I think this is fixed.

(I have seen occasional timeouts in the windows gui system tests, but I think that is a distinct issue)
