### ISSUE TITLE
Packaging for Windows build

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1430]
### Desired Behaviour

We need to provide a package on Anaconda that works on Windows. Initially this could just be a Conda package. Longer term it would be good to look into a more straight-forward installer for Windows, potentially packaging as a `.exe` file.

### Current Behaviour

The current published package specifies Linux and cannot be installed on Windows.

**Comment by rbauststfc** [comment]
Steps for this issue:

- [ ] Create a noarch package
- [ ] Figure out running the package nicely on Windows (even after activating the `mantidimaging-nightly` environment, this currently requires changing directory to `...\mambaforge\envs\mantidimaging-nightly\Scripts` and running `python mantidimaging`)
- [ ] Look into building on Windows as well as Linux
- [ ] Update the command that displays for updating an outdated Mantid version - currently get error `'source' is not recognized as an internal or external command, operable program or batch file` when run on Windows.

**Comment by samtygier-stfc** [comment]
The update command is somewhat IDAaaS specific. On IDAaaS we don't enable mamba for the user, so the sourcing is required. But any user installed system will either have mamba activated, or the user will know how to activate mamba. So could just give the `f"{self._conda_exe} update -c mantid/label/{suffix} mantidimaging"` part on windows.

**Comment by samtygier-stfc** [comment]
We could add it to the windows workflow with a different label (e.g. windows-build-test), that would mean it would show up on the conda repo, but would only get installed if you explicitly ask for it ( `-c mantid/label/windows-build-test`). Once we know it works, we can disable it.
