### ISSUE TITLE
Recon GUI system test timeouts on Windows

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1455]
The "Minimise error" button seems to take a little longer to become enabled on Windows and this causes some of the recon window GUI tests to timeout if the waits aren't set high enough.

**Comment by samtygier-stfc** [comment]
Is this related to #1442

**Comment by rbauststfc** [comment]
Ah yes, looking at the workflow run on issue #1442, it's the same error. There's the error that refers to teardown that's flagged in that issue, but then if you scroll further down it mentions failures in the wait in `test_refine_stress` and `test_refine`.

**Comment by rbauststfc** [comment]
We can close this issue if you'd rather investigate it under #1442, though?

**Comment by rbauststfc** [comment]
I'm going to close this issue in favour of the other as test failures on the draft PR suggest there's something more than it just being slow that's causing the wait to fail.
