### ISSUE TITLE
Investigate a packaging solution that allows simpler MI installation

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1462]
### Desired Behaviour

Find a packaging solution that simplifies the installation process - ideally Mantid Imaging installation would become a single step. There might also be some options we can explore to allow it to be started without having to run commands in a terminal, particularly on Windows. PyInstaller has been suggested as a good tool to look at for this.

### Current Behaviour

Current installation is as per the instructions here https://mantidproject.github.io/mantidimaging/installation.html. This requires installation of Conda, the CUDA runtime and gcc, as well as needing to run terminal commands to start the application.

**Comment by rbauststfc** [comment]
Here are some notes so far on PyInstaller.

### General info from the documentation:
- You have to package on different operating systems for specific Python versions and specific to 32 or 64 bit OS.
- You can create a Python script to run PyInstaller with the relevant options: https://pyinstaller.org/en/stable/usage.html#running-pyinstaller-from-python-code
- You can package as a single folder or single file. Recommend getting single folder working first as easier to debug issues.

Single file package:
- Apparently slower to start-up than the one-folder bundle.
- You can display a simple splash screen to indicate to the user that start-up has begun: https://pyinstaller.org/en/stable/usage.html#the-pyi-splash-module
- It won't work on Linux if the `/tmp` folder has been mounted with the no-execution option, as the single file creates a temp folder that runs from there.
- It won't share any files, so running multiple copies of the application works but uses lots of disk space.
- The temp folder is not removed if the program crashes or is killed. The temp folder has the naming convention: `_MEIxxxxxx`, where `xxxxxx` is a random number.
- You can define where the temp folder will be created using a command line option at packaging, although the documentation recommends you only do this if you "know what you're doing".

### Findings from experimenting with one-folder packaging:
- Getting `syspath` needs changing: https://stackoverflow.com/questions/404744/determining-application-path-in-a-python-exe-generated-by-pyinstaller
- Struggles to resolve some imports: https://stackoverflow.com/questions/25733467/no-module-named-when-using-pyinstaller. We need to pass in as part of the command: `--hidden-imports [missing.import]`
- Need to pass in ui files, images and any other non-binary files as data: `--add-data="path/to/folder/*;path/to/folder/"`. This grabs all files in the directory and specifies where to put them in the PyInstaller output. Note that any sub-folder structure is not maintained.
- There is an issue with multiprocessing on Windows when running a frozen version of the application, but a simple solution is provided for this: https://stackoverflow.com/questions/46335842/python-multiprocessing-throws-error-with-argparse-and-pyinstaller
- Given that some code will work when running the application as a script but won't work with the frozen executable, it may be good to find a way to test the packaging step as part of our CI process.

### Current packaging command being run and list of outstanding issues:
```
pyinstaller --hidden-import astra.utils --hidden-import tomopy --add-data="gui/ui/*.ui;mantidimaging/gui/ui/" --add-data="gui/ui/images/*;mantidimaging/gui/ui/images/" --add-data="gui/windows/wizard/*.yml;mantidimaging/gui/windows/wizard/" __main__.py
```
Note as well as running this command, I have made some small code changes to filepaths and multiprocessing to get the output application to start up. I think we would want the final solution to run this from a script rather than command line.

**Outstanding issues with the package output:**
- Tidying up the output, i.e. calling `__main__.py` outputs a package with the name `__main__` when we will want `MantidImaging` or similar. Look into whether there are options to re-name the output or whether the command should be using a different start point.
- Currently CUDA isn't being picked up, so only gridrec reconstruction is available.
- The Operations window doesn't open because of the method we're currently using to load the filter modules. Need to look into if/how we can still use `pkgutil.walk_packages` with the PyInstaller output.

**Comment by samtygier-stfc** [comment]
Thanks. I think the initial targets should be Linux, Windows, both with python 3.9 and 64 bit (we only ever targeted a single python version at a time, and don't need to worry about 32bit).

I think the initial work would be a script to build a one-folder package that will start up. The outstanding issues can then be dealt with as follow-up issues.

**Comment by rbauststfc** [comment]
### Outstanding issues - 16/12/2022

These are the things that I think still need looking at following [the first PR for this issue](https://github.com/mantidproject/mantidimaging/pull/1648). See the notes on that PR for the status of the changes so far.

- [ ] The order of the filters in the Operations window drop-down are different in the packaged application (although they are still grouped correctly into the different sections). These will need to be sorted in some way if we want to ensure the order always stays the same.
- [ ] If we want to stop requiring users to install Conda/Mamba then we need to remove any Conda/Mamba commands that are run in MantidImaging - for example, the application doesn't start up on a clean install because we try to check the version using Conda. After fixing this, further testing on a clean install (both Windows and Linux) is needed to identify if there are any more missing dependencies.
- [ ] It would be good to set the executable to use the MantidImaging icon. I believe there's a PyInstaller option for doing this.
- [ ] The package created is currently 2.5 GB, which takes a while to download, even when zipped to 1.1 GB. It would be good to investigate if there's anything being pulled into the package that isn't required and could be excluded.
- [ ] Consider if we would like to package to a single file. See [comment above](https://github.com/mantidproject/mantidimaging/issues/1462#issuecomment-1293260155) for some information about single file packaging and things we may need to consider.
- [ ] It's possible that future changes to imports in the code could break the packaging, so it would be good to have some automated tests to check for this if possible.

Long-term there will obviously be the decisions around how we're going to package and upload the application as part of releases, and where the package will be made available.

**Comment by samtygier-stfc** [comment]
With a quick test running it in a clean linux docker. I bypassed the finding conda issue and then hit

```
  File "tomopy/util/extern/__init__.py", line 98, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "tomopy/util/extern/recon.py", line 83, in <module>
  File "tomopy/util/extern/__init__.py", line 81, in c_shared_lib
ModuleNotFoundError: TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.
[486] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by rbauststfc** [comment]
> With a quick test running it in a clean linux docker. I bypassed the finding conda issue and then hit
> 
> ```
>   File "tomopy/util/extern/__init__.py", line 98, in <module>
>   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
>   File "tomopy/util/extern/recon.py", line 83, in <module>
>   File "tomopy/util/extern/__init__.py", line 81, in c_shared_lib
> ModuleNotFoundError: TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.
> [486] Failed to execute script '__main__' due to unhandled exception!
> ```

It would be worth checking the contents of the Linux package against the Windows one then, as tomo-recon is one of the tomopy dynamic libraries that we try to pull in using `add_conda_dynamic_libs` in the packaging script. On Windows this seems to grab everything OK, but perhaps something more is needed on Linux.

**Comment by samtygier-stfc** [comment]
Lets closes this as the initial work is done, and we have open issues for remaining issues.
