### ISSUE TITLE
Add a spectrum viewer dialog

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1498]
Placeholder for user requirements for this.

**Comment by samtygier-stfc** [comment]
Info in `Mantid Imaging > Documents > Planning > Quick ToF tools.docx`

**Comment by rbauststfc** [comment]
@samtygier-stfc I've pushed everything I've prepared on this to branch `1498-add-spectrum-viewer`, so you should be able to pick the branch up to start looking at the ROI side when you're ready. The things I've put in place are:

1) Adding "Spectrum Viewer" to the "Workflows" menu in the main window. Clicking this option opens the spectrum viewer in a new window (this is why I wasn't keen to put it into PR at this stage, although if this was temporarily removed the rest could probably go in if needed).

2) The layout for the new window has a splitter, the same as the recon and operations windows use, to separate the section for input fields and the section for the image. The layout is likely to need resizing/settings tweaks as you continue to work on it, particularly around what happens when you re-size.

3) I've setup the two dropdowns to populate with stacks from the main window using the DatasetSelectorWidget. The second dropdown can be enabled and disabled with a checkbox. For now I've left it so that the checkbox simply enables and disables the dropdown, I figured we could decide further down the line if there was a need for it to do anything with the contents of the dropdown when the state changes.

4) The second dropdown will automatically try to select a flat for the selected sample dataset, if one is available. I've noticed that if you keep the window open, delete all the datasets in the main window and then (with the window still open) reload a dataset it doesn't correctly select the flat. This seemed a very minor, niche issue and so I didn't want to delay handing this over to fix it. I can continue to investigate and comment here with anything I find about how to resolve it, though.
