### ISSUE TITLE
Separate ROI selector window into it's own class

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1613]
The ROI selector window (that opens from the Crop Co-ordinates and ROI Normalisation filters) is currently created by method `roi_visualiser` in the `FiltersWindowView` class. This method has grown to hold quite a lot of logic and defines a number of methods within it. It would be good to refactor this so that the ROI selector window is defined in it's own class and can be re-used easily if ever needed. It should also improve our ability to test the functionality of the window.

**Comment by samtygier-stfc** [comment]
Also make sure that the window closes in the gui system tests. See discussion on #1612
