### ISSUE TITLE
Formally Document Spectrum Viewer

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1717]
### Desired Behaviour

Formally document the Spectrum Viewer to complete umbrella issue #1618 to describe the Spectrum Viewer and its intended usage. 

### Current Behaviour

There is no formal documentation describing the Spectrum Viewer and its usage within Mantid Imaging documentation.

**Comment by samtygier-stfc** [comment]
Closed in #1735
