### ISSUE TITLE
SPDHG memory requirement calculation

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1720]
### Desired Behaviour
Update memory requirement calculation. In `CILRecon.full`

Should be lower for SPDHG.

**Comment by paskino** [comment]
Looking at the code

https://github.com/TomographicImaging/CIL/blob/8e78dfef2d3f49cef9e4ecf4dfdd7da2de6bcb66/Wrappers/Python/cil/optimisation/algorithms/SPDHG.py#L164-L177

The requirements are: 4 x the solution, 1 (+ the data) of size data, 1 subset. 
The latter could be a physical subset, i.e. a piece of the data, or 1 `ImageData` of the size of the solution. This will change per iteration, depending on what type of subset will be chosen.

In the end a conservative estimate is 5 x solution + 2 times the data.
