### ISSUE TITLE
Ruff for linting

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1783]
Investigate and switch to Ruff as a replacement for flake8

https://beta.ruff.rs/docs/

Possible advantages would be speed, enabling more linting options with (without have to add lots more flake8 plugins), in the future it might replace yapf and even mypy

**Comment by samtygier-stfc** [comment]
I assume ruff can just run on the source directory like the other tools, so shouldn't need to install.

I usually just run the local checks manually with the makefile and automatically with pre-commit. I'm happy to have tox if it makes life easier.

**Comment by JackEAllen** [comment]
> 

I think the main advantage is to speed things up in CI if using alongside Tox

**Comment by JackEAllen** [comment]
use pre-commit run-all-files when exploring this

**Comment by samtygier-stfc** [comment]
Closed by #1847
