### ISSUE TITLE
Mantid Imaging - Rotating after cropping causes loss of data

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantidimaging#1805]
### Summary

**Raised by user Hamish_C** https://forum.mantidproject.org/t/bug-mantid-imaging-rotating-after-cropping-causes-loss-of-data/857

Had a quick search of issues, doesn't look like this is a duplicate.

### Steps To Reproduce

"Open an image in Mantid Imaging. Go to Workflow → Operations. Perform a crop to some non-square aspect ratio. Perform a 90 degree rotation."

### Expected Behaviour

"When performing operations on a stack, if you choose to crop the stack to a non-square aspect ratio and then rotate the stack, you would expect that the “aspect ratio” also “rotates”, e.g. if you have a stack that has been cropped to have a width of 2 and a height of 1, and you rotate it by 90 degrees, you would expect the width to become 1 and the height to become 2, and all of the original data to still be represented."

### Current Behaviour

"The aspect ratio of the final image (after rotation) is kept identical to before rotation, combined with a loss of data and addition of black bars to fill the space."

### Context

"I am using this on IDAaaS at the moment, I believe the same happens in either the stable or unstable builds that are present on IDAaaS right now."

### Screenshot(s)

![image](https://github.com/mantidproject/mantidimaging/assets/95620982/6417db72-149b-4768-beab-af9a41afbf38)

**Comment by JackEAllen** [comment]
Snap aspect ratio to closes 90 degrees of rotation. If custom input of <=45 don't change aspect ratio, if custom input >=46 snap to 90 degrees

**Comment by samtygier-stfc** [comment]
QComboBox to choose 90, 180, 270 or custom.
