### ISSUE TITLE
User Bug Report: Load Data Doesn't Find Flat and Dark Folders and Filenames

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1865]
### Summary

Mantid Imaging no longer finds flat and dark folders and filenames after selection of sample projections.

### Steps To Reproduce

* Open Mantid Imaging
* Load a Sample selecting sample projections
* Notice that Flat and Dark folders are not loaded

### Expected Behaviour

Flat and dark folders should be loaded automatically.

### Current Behaviour

Flat and dark folders are not loaded automatically.

### Context

Latest Nightly build.

**Comment by samtygier-stfc** [comment]
The tomo file is
`.../Tomo/IMAT00026734_xxxx_Tomo_000.tif`

so we look for a flat before like (we look for a directory and filename with "Tomo" switched to "Flat_before", and a couple of variations)
`.../Flat_Before/IMAT00026734_xxxx_Flat_Before_000.tif`

But it actually has a different IMAT number
`.../Flat_Before/IMAT00026732_xxxx_Flat_Before_000.tif`

Given that it is now common for flat and dark to have different experiment numbers, it has been decided to make the finder less strict, and give the first image file found in a folder that matches the expected name. So we should now match.

`.../Flat_Before/anything_000.tif`
