### ISSUE TITLE
Spectrum Viewer: RITS Front-End GUI

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1941]
### Desired Behaviour

Create a basic front-end GUI for exporting to RITS format within the spectrum viewer.

### Criteria
* RITS export should be accessible via a tab in the spectrum viewer window as denoted in the wireframe design below.
* One ROI, the same size as the FoV should be initially loaded similarly to default spectrum viewer state.
* It should be possible for the ROI to be resized and repositioned within the bounds of the FoV.
* A numeric entry box should be provided to allow users to set the binning size.
* A separate box should also be included to set the moving average.
* The export RITS button should export the ROI spectrum data in RITS format.

![image](https://github.com/mantidproject/mantidimaging/assets/32413847/30fa6f0f-bd5d-4f92-8486-19571c183212)

### Current Behaviour

There is currently no front-end GUI for exporting to RITS format within Mantid Imaging.

**Comment by samtygier-stfc** [comment]
With #2010 done, we can close this
