### ISSUE TITLE
Use percentiles rather than min max for auto brightness levels in live viewer

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1964]
### Desired Behaviour

When displaying a new image in the live viewer, use the 5%-95% percentiles to set the brightness range rather than the min and max. This would prevent a small number of outlier pixels skewing the levls.

For this to be useful it needs to not be significantly slower that existing min/max method. An approximate algorithm would probably fine.
Hopefully there is a useful method in https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

The code for displaying images in the live viewer is in:
~~mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py~~ `mantidimaging/gui/windows/live_viewer/live_view_widget.py`
and the MIMiniImageView widget (note this is used in other places)
`mantidimaging/gui/widgets/mi_mini_image_view/view.py`

Will also be useful to look at how we use the pyqtgraph `ImageItem`
https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/imageitem.html

**Comment by MikeSullivan7** [comment]
Isn't the code of the live viewer in `mantidimaging/gui/windows/live_view_widget.py` rather than `mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py` ?

**Comment by samtygier-stfc** [comment]
Yes, sorry.
