### ISSUE TITLE
Spectrum Viewer: Change ROI Colour Through Right Click Dialog Menu

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1992]
### Desired Behaviour

From the image view, spectrum line plot or table of ROIs, provide a right click dialog menu allowing a user to set a new colour for a given ROI. Only colours provided by `mantidimaging.gui.windows.spectrum_viewer.spectrum_widget.colour_generator` should be made available. 

### Current Behaviour
It it not possible to change an ROIs colour once added. 

The current work around for this is to delete the ROI and add a replacement ROI which will be given the next colour in the list from the previous colour. 
The list of colours can be found here: `mantidimaging.gui.windows.spectrum_viewer.spectrum_widget.colour_generator`
The list tries to use colours that are visible for users who may have varying levels of colour blindness.

**Comment by samtygier-stfc** [comment]
I think this should also work by clicking the colour on the ROI table.

We could show a QColorDialog and let the user pick any colour.
