### ISSUE TITLE
Live Viewer: Rotate Images

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#2003]
### Desired Behaviour

Some cameras are mounted at different angles meaning arriving data is not always displayed at the correct angle.

Customise right click menu of image within Live Viewer to rotate all images within by 90, 180 or 270. 
For a given selected angle, all existing images and newly arriving images should be rotated to the new angle so a user does not need to keep re-selecting a new angle for every new image which arrives.

I recommend placing this in a right menu over the image to minimise UI changes to the Live viewer itself. 

Users like the Live Viewer window to be minimal to leave on a monitor maximised.

To tackle this issue, use existing rotate stack code from operations window:
- `mantidimaging/core/operations/rotate_stack/rotate_stack.py`

This issue will act as a good test for moving existing operations to work with live/changing data stacks which currently, they are not.

### Current Behaviour

Live data can not be rotated.

![image](https://github.com/mantidproject/mantidimaging/assets/32413847/47fc0a1f-bbb0-4edb-bf53-f670438139bb)

**Comment by samtygier-stfc** [comment]
Closed by #2021
