### ISSUE TITLE
operations_tests.py improvements 

### ISSUE THREAD

**Issue by ashmeigh** [mantidproject/mantidimaging#2061]
Add ConfigurationManager class for paths and environment variables

Use the TestRunner class to simplify the main function, clearly separating configuration and execution phases.

Add logic for running tests, including loading image stacks and comparing results, directly into the TestCase class.

ImageStack Class for loading, saving, and managing image stacks.

Add more explicit error handling and logging throughout the code

Look at the parallel processing once the compute functions have been added 

Csv file for progress updates??

**Comment by samtygier-stfc** [comment]
As we discussed, there are a few operations were the current test_cases.json can't express everything thats needed. Here we may need some special functions that modifiy the test data, which the json file can the request to be called.

* Monitor normalisation - add monitor metadata

Also, where the current data does not make a strong test.

* NaN removal - add some NaNs into the test data
