### ISSUE TITLE
Add / Replace Image Stack doesn't allow .fits files

### ISSUE THREAD

**Issue by MikeSullivan7** [mantidproject/mantidimaging#2152]
### Summary

Loading any extra files through the "Add / Replace Image Stack" dialog does not allow the selection of .fits files

### Steps To Reproduce

Open MI and load data, then right click the data stack on the tree on the left and click "Add / Replace Stack". Clicking the "Choose File" button only allows .tif and .tiff files to be selected.

### Expected Behaviour

The  "Add / Replace Stack" should be able to load the same file types as the main Load Dataset file dialog.

### Current Behaviour

Only .tif and .tiff files can be loaded though the  "Add / Replace Stack" file dialog

**Comment by MikeSullivan7** [comment]
It seems that the "Add / Replace Image Stack" dialog doesn't work at all anymore, even with .`tif` or `.tiff` files.

```
2024-08-15 15:02:35,090 [mantidimaging.gui.windows.main.view:L589] ERROR: Traceback (most recent call last):
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\gui\windows\add_images_to_dataset_dialog\view.py", line 37, in _on_accepted
    self.presenter.notify(Notification.IMAGE_FILE_SELECTED)
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\gui\windows\add_images_to_dataset_dialog\presenter.py", line 29, in notify
    self.load_images()
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\gui\windows\add_images_to_dataset_dialog\presenter.py", line 37, in load_images
    start_async_task_view(self.view, self.view.parent_view.presenter.model.load_image_stack,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindowModel' object has no attribute 'load_image_stack'
```

**Comment by MikeSullivan7** [comment]
It seems like this has been broken as far back as `release-2.7.0` which is confusing as I thought this would be caught in manual testing...

**Comment by MikeSullivan7** [comment]
The error is still showing in `release-2.6.0` after rebuilding the dev environment (after swapping out the old intel channel)

**Comment by samtygier-stfc** [comment]
https://github.com/mantidproject/mantidimaging/pull/2317 is the fix for Add/Replace on an open dataset, which has been broken for a while.

The File->Load Images method (which makes a new dataset with the new stack) works for tif but not for fits. That's probably the method that this issue should be about.

**Comment by JackEAllen** [comment]
This may be related to and solve: #2397
