### ISSUE TITLE
LiveViewer: Out of Synchronisation with Most Recent Image - Difference Increases with Dataset Size 

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#2204]
### Summary

"We have been recording radiography images at an exposure time of 5s/image and find that there is a considerable lag for the Live Viewer images to get updated. It took ~3 minutes to display the new image this morning and there was a lag between the image that was displayed and the image being currently collected (the displayed image was more than 100 images behind the one currently being collected). 
Once the user restarted Mantid, the lag was less, but still around 7 to 8 images behind."

"To add context, the current experiment produces images every 5 seconds, so 12 hours of scan will produce 8000+ images. I think we're targeting the parent RB folders so probably the live viewer struggled to scan through that many images to display the latest one."

### Steps To Reproduce

- Create a dataset of ~8000 tiff files
- Create an output directory to copy images too
- Open Mantid Imaging Live Viewer and select output directory
- Run live viewer simulation script to copy files from fake dataset to output directory
- Watch images to see if they fall out of sync

### Expected Behaviour

Live viewer should always show the newest file written within watched directory.

### Current Behaviour

Live viewer fall out of sync with newest image written to directory after so many images within a large dataset.

### Context

Discovered by IMAT when using live viewer to watch 12 hour of scan will produce 8000+ images. Acquisition time was ~5 seconds.

**Comment by JackEAllen** [comment]
I have managed to replicate with a dataset of 8000 tiffs. The live viewer fell out of sync at image 2250 where the most recent image written was 2278 using the simulate live viewer utility script.

**Comment by JackEAllen** [comment]
Can't say if it's the same issue with certainty, but second time round, running the same test, MI became unresponsive after falling out of sync when selecting the live viewer window.

![Image](https://github.com/mantidproject/mantidimaging/assets/32413847/ea31d644-8e13-4d65-a718-5dfe0624905f)

```bash
2024-05-15 09:01:45,608 [mantidimaging.core.parallel.manager:L40] INFO: Creating process pool with 8 processes
2024-05-15 09:02:27,296 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
2024-05-15 09:02:45,515 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
2024-05-15 09:03:29,124 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::addPaths: list is empty
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::addPaths: list is empty
QFileSystemWatcher::removePaths: list is empty
```

**Comment by JackEAllen** [comment]
> Can't say if it's the same issue with certainty, but second time round, running the same test, MI became unresponsive after falling out of sync when selecting the live viewer window.
> 
> ![Image](https://private-user-images.githubusercontent.com/32413847/330753913-ea31d644-8e13-4d65-a718-5dfe0624905f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3Njg4MTksIm5iZiI6MTcxNTc2ODUxOSwicGF0aCI6Ii8zMjQxMzg0Ny8zMzA3NTM5MTMtZWEzMWQ2NDQtOGUxMy00ZDY1LWE3MTgtNWRmZTA2MjQ5MDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEwMjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2M2YzMDJjZTA1OWU1NDRiNWYwYTg3OWFhYmU2YmFlNTI0OWRkMDliNWFkZThkYzc3NjQ0ODRjZDhlMzY5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ttRinZOgZ1kjI8zI4UdBf1dSel65lINDIX_eAlSWLQ)
> 
> 2024-05-15 09:01:45,608 [mantidimaging.core.parallel.manager:L40] INFO: Creating process pool with 8 processes
> 2024-05-15 09:02:27,296 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
> 2024-05-15 09:02:45,515 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
> 2024-05-15 09:03:29,124 [mantidimaging.gui.mvp_base.view:L35] DEBUG: UI window closed
> QFileSystemWatcher::removePaths: list is empty
> QFileSystemWatcher::addPaths: list is empty
> QFileSystemWatcher::removePaths: list is empty
> QFileSystemWatcher::addPaths: list is empty
> QFileSystemWatcher::removePaths: list is empty
> When clearing the watched directory of files, the window becomes responsive again

So from testing a third time, i noticed that the python process switch's between responsive and unresponsive when slow down occurs so we are definitely reaching an upper threshhold somewhere. When the switching from unresponsive to responsive and back, this is when the live viewer updates to a newer image which has since become not the newest image written.

**Comment by JackEAllen** [comment]
When python becomes unresponsive, the live viewer still acknowledges new file changes coming in and sends calls to qt to update the image view with the newest file, despite the image not updating.

**Comment by samtygier-stfc** [comment]
I can reproduce on windows (but not on linux)

Using `simulate_live_data_stress.py` from the `2204-test-script` branch, creating a folder full of 128x128 images.

With
`python scripts\simulate_live_data_stress.py -d \Users\sid34479\AppData\Local\Temp\mi_test\live -s 0 -f 500 -r 0.01 -v`
MI goes unresponsive for a minute

**Comment by samtygier-stfc** [comment]
With a `ExecutionTimer` in `_handle_directory_change` I can see that it slows down on windows as the number of files grows. For me by 3000 files it takes about a second. It looks to me like once the files are arriving fast than it can handle the event queue starts to build up, so UI stop responding, and the signals we use to show the new image have to wait a long time in the queue.

I think there are 2 approaches to fixing.
1) Look for ways to make the the handling of new events faster. Is there some bad scaling, or is it just slow to check the age of every file?
2) A way of absorbing many signals on the queue quickly, and then doing the work once.

**Comment by samtygier-stfc** [comment]
Looks like 80% of the time is in stat, i.e. checking the age of the files.

```
INFO: inner_handle_directory_change:
INFO:          166473 function calls (166434 primitive calls) in 1.058 seconds
INFO:
INFO:    Ordered by: cumulative time
INFO:
INFO:    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
INFO:         1    0.000    0.000    1.058    1.058 C:\...\\gui\windows\live_viewer\model.py:231(inner_handle_directory_change)
INFO:      6004    0.007    0.000    0.843    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:1092(stat)
INFO:      6004    0.790    0.000    0.836    0.000 {built-in method nt.stat}
INFO:         1    0.005    0.005    0.558    0.558 C:\...\\gui\windows\live_viewer\model.py:200(find_sub_directories)
INFO:         1    0.014    0.014    0.477    0.477 C:\...\\gui\windows\live_viewer\model.py:185(find_images)
INFO:      3001    0.008    0.000    0.437    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:1300(is_dir)
INFO:      3000    0.008    0.000    0.426    0.000 C:\...\\gui\windows\live_viewer\model.py:38(__init__)
INFO:      3001    0.002    0.000    0.117    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:1023(glob)
INFO:      3001    0.008    0.000    0.114    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:487(_select_from)
INFO:      6003    0.017    0.000    0.051    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:668(__hash__)
INFO:      6008    0.008    0.000    0.046    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:631(__fspath__)
INFO:      3001    0.019    0.000    0.040    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:438(_select_from)
INFO:      6009    0.022    0.000    0.038    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:621(__str__)
INFO:      3005    0.009    0.000    0.032    0.000 C:\...\AppData\Local\mambaforge\envs\mantidimaging-dev\lib\pathlib.py:654(_cparts)
```
