### ISSUE TITLE
Update numpy and scipy

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2268]
### Desired Behaviour

Update to numpy ~~2.26~~ 1.26 and 1.14

**Comment by MikeSullivan7** [comment]
I think you mean numpy 1.26?

**Comment by MikeSullivan7** [comment]
Note: Scipy 1.14 has removed `interp2d`

We will need to transition via https://docs.scipy.org/doc/scipy/tutorial/interpolate/interp_transition_guide.html#interp-transition-guide
