### ISSUE TITLE
Not enough storage space during Ubuntu and Rocky8 Builds

### ISSUE THREAD

**Issue by MikeSullivan7** [mantidproject/mantidimaging#2313]
### Desired Behaviour

During the Github Action of rebuilding the Ubuntu and Rocky8 Dockers, both Docker Images should build successfully.

### Current Behaviour

If the packages become too large (e.g. with the inclusion of the `Dask` dependencies), then both Dockers do not build successfully within the same Github Action file due to lack of storage space. This seems to be due to `docker/build-push-action@v4` not doing the Post Cleanup until the end of the job list, i.e. the first Docker build is not purged before the next one is built. 

Solutions could include:
Forcing the Docker Post Cleanup before the next Docker Image is built
Using a stripped back version of the images to save on space.
Separating the Ubuntu and Rocky8 Docker build into different Action files.

**Comment by samtygier-stfc** [comment]
Might be useful to look at `docker image list` before and after to see image sizes. Also `docker image prune -a` might be a better prune command that what we tried last week.
