### ISSUE TITLE
Multiple Qt bindings packages in PyInstaller

### ISSUE THREAD

**Issue by MikeSullivan7** [mantidproject/mantidimaging#2330]
### Summary

PyInstaller fails as it does not support multiple Qt bindings due to Pyside6 and PyQt5.

### Steps To Reproduce

run `python PackageWithPyInstaller.py`

### Expected Behaviour

Windows .exe should build successfully

### Current Behaviour

PyInstaller aborts part way through the build

### Context

Running `PackageWithPyInstaller.py` on current `main`

### Failure Logs

```
Aborting build process due to attempt to collect multiple Qt bindings packages: attempting to run hook for 'PySide6', while hook for 'PyQt5' has already been run! PyInstaller does not support multiple Qt bindings packages in a frozen application - either ensure that the build environment has only one Qt bindings package installed, or exclude the extraneous bindings packages via the module exclusion mechanism (--exclude command-line option, or excludes list in the spec file).
```

**Comment by samtygier-stfc** [comment]
Do you know how pyside got into your environment? I don't think any of our requirements should include it. It does not appear to be in my environ on linux.
