### ISSUE TITLE
Overlap Correction as standalone script

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2332]
### Desired Behaviour

An initial implementation of Overlap correction #2115 as a stand alone script that can be run on a folder of TIF/FITS files.

Some diagnostics and plotting, so that IMAT can check and confirm the behaviour and compare to their existing methods.

**Comment by samtygier-stfc** [comment]
Initial work at https://github.com/samtygier-stfc/mantid_imaging_scripts

**Comment by JackEAllen** [comment]
IMAT have voiced they are happy with this so marking as done for now
