### ISSUE TITLE
Drop Python 2.x support

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantidimaging#240]
As Conda is used for packaging there is no real need to keep supporting both Python 2.7 and 3.5. Before the first release I'd like to drop support for Python 2.7.

- Packaging is not an issue due to Conda
- It is unlikely the GUI package will ever have to interact directly with Savu (and even then not with anything outside of process list configuration) so dependency requirements are not an issue

@martyngigg Can you think of anything that would be stopping this from being done?

**Comment by martyngigg** [comment]
The only issue would be if `mantid` starts being used before we are ready but we do have a conda build so we should be able to add one for python 3.5.

**Comment by DanNixon** [comment]
If Mantid is used it will be via Savu, so for the GUI it should not be an issue.

**Comment by martyngigg** [comment]
I see. I don't see any other issues then.
