### ISSUE TITLE
Show 3 decimal places in spectrum viewer ToF properties

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2419]
### Desired Behaviour

For the flight path and time delay, show 3 decimal places

### Current Behaviour

Only 2 decimal places shown

**Comment by samtygier-stfc** [comment]
Wait until #2380 is done

**Comment by ashleymeigh2** [comment]
In the view.py file, the QDoubleSpinBox widgets flightPathSpinBox and timeDelaySpinBox add 

self.flightPathSpinBox.setDecimals(3)

This seems to solve the problem.
