### ISSUE TITLE
Automatically start SAVU Docker Backend on Mantid Imaging start

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#325]
Now that GUI is using async functions, the SAVU backend can be another coroutine.
The following should be implemented:
- The SAVU startup and GUI coroutines start async
- The GUI coroutine registers itself as a progress/report callback of SAVU startup OR the SAVU startup notifies the GUI coroutine of status.
  - This way we can display status of the startup to the user, as well as any errors.

What the code needs to do:
- [x] Check for docker in PATH or common locations (snap/bin)
- [x] Start Docker container on a separate thread
- [x] Close Docker container on window close
- [x] Connect to existing Docker container if the port is taken

Next steps
- [ ] Refactor `preparation.py` into some sensible structure

**Comment by WHTaylor** [comment]
Closed by #356

**Comment by WHTaylor** [comment]
Wrong issue
