### ISSUE TITLE
Stack Visualiser add rename window back

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantidimaging#334]
Make sure to address #190

Initial work for this issue is done on branch `334_add_missing_context_options_on_stack_vis`.

What is left to be done:

- Add rename context action, and actually change the name of the stack in the stack visualiser. The name is just the stack visualiser dock's windowTitle. A property is available, but it only has a getter. A setter should be added.

Follow up issues
#335 #336

**Comment by WHTaylor** [comment]
Closed by #356
