### ISSUE TITLE
Clarify LOCAL_DATA_DIR usage for users

### ISSUE THREAD

**Issue by WHTaylor** [mantidproject/mantidimaging#401]
With the current setup of hebi/savu running in a container, it is only possible to use savu filters/process lists on images which are stored in the directory tree under the directory specified by `savu_backend_docker.RemoteConfig.LOCAL_DATA_DIR`. This is assumed implicitly in the savu_filters model, but it is not told to the user, nor validated for anywhere - trying to run a savu filter on files outside of the directory which is mounted into the container results in a pretty impenetrable error from hebi.

Options:
 - Notify users that only files under that particularly root can be used.
 - Restrict stack loading (possibly also saving?) to only folders under `LOCAL_DATA_DIR`.
 - See if it's possible to add volumes to container whilst it's running, or equivalent (looks maybe possible, but awkward).

**Comment by dtasev** [comment]
Removed with recent refactor.
