### ISSUE TITLE
Histogram in Filters window shouldn't change range when preview is calculated

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#484]
#### Current behaviour
Zooming in on a region of the histogram and then changing a filter parameter will fully reset the histogram.

#### Desired behaviour
The histogram is not reset on parameter change - this allows focussing on a part of the histogram and seeing how it changes with parameters, without having to find the same bit every time.

The histogram should still be reset on filter change.

-----------

The histogram view has two modes - combined, and 2 independent histograms (for before/after). They are stored as different objects, so initially the focus should be on the combined one, and the code be reused as follow-up work.

Notes:
- The relevant histogram objects are in `mantidimaging.gui.windows.filters.filter_previews`, possibly the necessary changes can be only in `draw_combined_histogram`, but this is not a guarantee!
- Filters that change the shape of the data (e.g. crop) do not have histograms

**Comment by Pasarus** [comment]
I am not sure this still happens, need to confirm meaning. I assumed this means inside of filters under workflow after load. @dtasev we best make sure this isn't already implemented.
