### ISSUE TITLE
Relative Imports Issue - IPython doesn't work properly after cd-ing into another directory

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantidimaging#57]
When starting `ipython` with the `mantidimaging-ipython.sh` script, the package will work fine unless we `cd` into another directory. At this point all of the relative imports will fail, as they will be relative to the directory we `cd`ed into. 

A fix for this might be to replace the relative imports with absolute imports.

**Comment by DanNixon** [comment]
I can't reproduce this.
It could be an issue with the way the IPython environment used to be launched but for a globally accessible Python module having changed directory should not matter.
