### ISSUE TITLE
Total available memory should use the mount size of `/dev/shm`

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#608]
The size of the mount can be found by `findmnt | grep /dev/shm` and cropping the number after `size=...k`. I am not sure whether this value is in bits or bytes (the total memory from `psutil` is in bytes) so that needs to be checked.

- This means that we don't need `psutil` anymore, but we may as well keep it, in case the shell call fails?
- A warning could be shown to the user telling them they should run `sudo mount -o remount,size=100% /dev/shm` to get access to the full available RAM

**Comment by Pasarus** [comment]
I don't think this works well for what we want to do, psutil does as good a job as I think we can, having looked at other methods.

**Comment by dtasev** [comment]
Not quite as `psutil` always gives 100% of available memory, so in that case where the user hasn't allowed 100% we will crash unexpectedly. Could also be an additional way to tell the users to run the remount. Not a high priority but I think we should keep it open for now

**Comment by samtygier-stfc** [comment]
Not needed since switching from SharedArray
