### ISSUE TITLE
Change filters to use a similar structure to tools with an AbstractFilter

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantidimaging#62]
The `tools` module uses `AbstractTool` to 'enforce' an interface to any classes deriving from it. A similar approach could be taken with the filters, provide an `AbstractFilter` that will force the filter to implement an `execute` function, and any other helper functions that are necessary to all filters.

**Comment by DanNixon** [comment]
I'm pretty much against this.

Filters do not have a state or represent a tangible thing, therefore they should not be represented in a program as a class.

Doing so would only add more code to maintain and add complexity to the API for users who wish to write their own scripts.
