### ISSUE TITLE
Fix failing GPU/Median filter tests

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [mantidproject/mantidimaging#625]
A few of them are using a numpy array rather than an `Images` object.

**Comment by samtygier-stfc** [comment]
A GPU/CUDA runner is needed before this can be used. We would need to host this ourselves, maybe on an STFC VM. Removing from the milestone for now.

**Comment by samtygier-stfc** [comment]
I slightly misunderstood earlier. The test fixes are useful even if we can currently only run them locally. I'll take a look at those.
