### ISSUE TITLE
Startup scripts do not work on SCARF 

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantidimaging#66]
The startup scripts `mantidimaging.sh` and related, do not work on SCARF as they assume `$HOME/mantidimaging` for the directory. A quick fix for this is to change the remote path to be the correct one -> `/work/imat/mantidimaging`. The path creation could be addressed automatically if an install script is added.

**Comment by DanNixon** [comment]
Just to add some more comments to this.

#69 removed the requirements for the `mantidimaging` package to be in a given location or the first item on the Python path and for Anaconda to be available in the home directory.

Now the `mantidimaging` scripts can be installed anywhere and be anywhere on the Python path and Anaconda can be installed anywhere and the `bin` directory be provided via the `MANTIDIMAGING_PYTHON_BIN` environment variable.
