### ISSUE TITLE
Friendly error message if CUDA not present

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#736]
If run on a system without CUDA (i.e. one without an NVidia GPU) then opening the reconstruction window with cause mantidimaging to crash.

To reproduce:
1) load a data set
2) Workflows -> Reconstruct

```
Error: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version.
Error: Failed to allocate 2048x2048 GPU buffer
python: ./../../src/CudaReconstructionAlgorithm2D.cpp:293: virtual void astra::CCudaReconstructionAlgorithm2D::initCUDAAlgorithm(): Assertion `ok' failed.
Aborted
```

**Comment by dtasev** [comment]
From Slack discussion with Dolica: 

Checking for CUDA with `nvcc` isn't reliable - IDAaaS has the CUDA Toolkit but the nvcc executable is not on PATH by default (and I couldn't find where it's hidden, `locate nvcc` gives back a path to a matlab installation). There also seems to be an issue with actually catching the exception that is raised as it's a C++ exception.

An implementation that was discussed:

- Check if `nvidia-smi` exists 
	- Although this only guarantees that the user has NVIDIA Drivers installed, not the CUDA toolkit 
	- Perhaps we can add a `locate libcuda` (case important) call? That seems to reliably find it, but it's in different places on different linux distros (CentOS seems to be `/usr/lib64/libcuda.so`, Ubuntu `/usr/lib/i386-linux-gnu/libcuda.so`, maybe this catches enough linux distros to be OK?)
- If exists then proceed using `FBP-CUDA`
- If not, then change recon algorithm to `gridrec`, this is CPU based and should work on anything

**Comment by samtygier-stfc** [comment]
Would the checks in `mantidimaging/core/gpu/utility.py` work?

**Comment by dtasev** [comment]
Another possibility I just remember about [astra.use_cuda](http://www.astra-toolbox.com/apiref/astra.html#astra.astra.use_cuda). I'm not sure about the gpu utility checks, it's worth looking at those as well, but they may be CUPY specific

**Comment by DolicaAkelloEgwel** [comment]
Yeah, it just checks if cupy can add two arrays.
