### ISSUE TITLE
Separate release and unstable packages documentation

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#743]
What's the best way to handle this? Currently we publish the docs on the gh-pages branch. Note that if we change the structure there we will have to update the links in the code, or they might end up invalid.

Perhaps if we can publish versioned docs this could be easy. I've seen this on ReadTheDocs packages, but I'm not sure if it is a ReadTheDocs feature or a Sphinx feature.

The fastest, but perhaps not best or easiest way, would be to keep the docs inside gh-pages as sub-folders for each version:
```
.
|--- index.html
|
|--- v1.0.0/docs for this version
|
|--- v1.5.0/docs for this version
|
|--- v....
|
|--- unstable
```

**Comment by Pasarus** [comment]
https://docs.readthedocs.io/en/stable/versions.html

**Comment by dtasev** [comment]
@samtygier-stfc Could you have a look at this?

The docs building is controlled via `setup.py` with 3 commands: 
- `docs_api` - generates the API pages, using the docstrings in the code
- `docs` - generates HTML from the RST pages, links to the generated API 
- `docs_publish` - publishes the docs to the branch `gh_pages` in this repo. I think currently it makes an empty repository in the `docs/build/html` folder, then essentially does a `git add .` and force pushes to overwrite everything in the `gh_pages`

Maybe the easiest way would be to add the version folders making the docs link for a version `http://mantidproject.github.io/mantidimaging/1.1.0/`. Otherwise it seems we might have to move to readthedocs and I don't know how much effort that would be.

**Comment by samtygier-stfc** [comment]
Staying with githubpages I think there are 2 approaches.

1. Make doc_publish checkout the existing docs, and copy the new updates into appropriate place and commit them. When a release is made it starts writing into a new folder, so that the old one is kept.

2. Built all the historic docs from scratch each time. Have a list of commits to checkout, build the docs and place into the right places.

2 might make it easier to apply changes to old versions (e.g. information in the side bar pointing to new info, updates to links).

**Comment by samtygier-stfc** [comment]
[sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html) does some of what is needed. It can build the docs for each tag (and or branch) that match a regex, and provides the versions list in the side bar.

It does not seem able to override the names it gets from git, so might need a little work to have "Unstable" and "Latest".

**Comment by samtygier-stfc** [comment]
We can use normal process to build top level docs of current checkout, this will give the 'latest' version that we would point links at:
https://mantidproject.github.io/mantidimaging/index.html
Then sphinx-multiversion to build versioned subdirs
https://mantidproject.github.io/mantidimaging/1.1.0/index.html
https://mantidproject.github.io/mantidimaging/2.0.0/index.html
...

We can use template overrides to make nice sidebar links between them. Within the versioned directories we get deep links between pages, which is smart about different pages between versions. I don't think I can easily replicate this between versioned and top level.

API stubs (docs/api) are not in git as they are generated. Need to patch sphinx-multiversion to run sphinx-apidoc before sphinx-build.
