### ISSUE TITLE
Dependency clean-up

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#764]
Examine the dependencies in `conda/meta.yaml` and determine which are no longer necessary

**Comment by samtygier-stfc** [comment]
`socketio`
I can't see this used any more. Also requested in `setup.py`

`requests-futures`
I can't see this used any more

`requests`
Used once in `version_check.py`, but could probably be replaced by std lib urllib

Not in `conda/meta.yaml`
`hazelnut`
In `deps/dev-requirements.pip` and `environment.yml` but no longer used.

`mock`
replaced by `unittest.mock`
Still in `environment.yml`

`isort`, `pytest-randomly`, `pytest-paralle`
in `environment.yml`. Is this useful, should we add a rule in the makefile to run it?
