### ISSUE TITLE
Remove NaN operation

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#819]
### Desired Behaviour

A wrapper around this: https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html

**Comment by samtygier-stfc** [comment]
Thinking more about this, we should also understand where the NaNs are coming from and how they might effect the output results.

One case seems to be doing a reconstruction without first doing a remove outliers. So maybe the recon tools can warn about values that will cause issues.

**Comment by samtygier-stfc** [comment]
It should be choose the value that the NaNs are replaced with.
