### ISSUE TITLE
Setup CI on Jenkins

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantidimaging#82]
For now a manual build of `master` with Anaconda Python 2.7 and 3.5 running nosetests.

**Comment by DanNixon** [comment]
This Jenkins job shows this working with a pipeline build: http://builds.mantidproject.org/view/Imaging/job/mantidimaging-master/7/

**Comment by martyngigg** [comment]
@DanNixon Are we getting close to being able to set this up to check the PRs?

**Comment by DanNixon** [comment]
There are still Python 2.7 tests failing (that are expected as they also fail on my machine), for some reason the Python 3.5 tests fail when they run fine locally.

Ideally I'd like to have the Python 3.5 tests reliably working before checking PRs too.

**Comment by DanNixon** [comment]
Cool, the tests pass for both 2.7 and 3.5 now: http://builds.mantidproject.org/view/Imaging/job/mantidimaging-master/13/

**Comment by DanNixon** [comment]
@martyngigg I think this is pretty much done now.

Feel free to repoen this if there is something I've missed.
