### ISSUE TITLE
Operation help goes to wrong page

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#820]
### Summary

The help for any filter below the first separator (`--------`) goes to the wrong help page.

This seems to happen in the `mantidimaging/gui/windows/operations/view.py::open_help_webpage` function, the `currentIndex()` no longer returns the correct index as we now have separators inside the list.

A crude fix for this was done in #821 but that will be contained only for the release branch.

### Steps To Reproduce

- Open Operations window
- Select Divide
- Click the `?` for help
- The web page opened will not be for the divide filter

### Expected Behaviour

The help page should always be correct

**Comment by samtygier-stfc** [comment]
#821 Merged, but keeping bug open for more general fix.
