### ISSUE TITLE
Automatically transpose grayscale palette to a color palette

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#823]
### Desired Behaviour

Have a button (or some other way to access the feature) that converts the grayscale palette into a color palette that tries to assign different colors to each material in the sample.

Two things are needed:
- Check if we can programmatically control the color scale of ImageView
- Find an algorithm that can produce good scale points for each color from the histogram

**Comment by samtygier-stfc** [comment]
Anna suggests the Otsu method. Also Jenks method may worth trying.
