### ISSUE TITLE
Ops window, pixel value not updating for part of image

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#940]
### Summary

User reported issue

Normally in the operations window, as the cursor is moved around the image the pixel value display at the bottom of the image is updated

![image](https://user-images.githubusercontent.com/74248560/115581878-50537780-a2c0-11eb-95b6-5ce17fcb15b0.png)

Sometimes this value stops updating for some region of the image

### Steps To Reproduce

~~I have been unable to reproduce locally or in IDAaaS yet~~

Open a dataset. Crop so that the images are taller than they are wide.

Happens in the recon window too.

### Expected Behaviour

Value is updated on mouse movement

### Current Behaviour

Sometimes it is not updated for some regions of the image

### Context

Occurred on IDAaaS with a nightly from April 6th.

It is possible this was a due to an issue with the IDAaaS web interface.

**Comment by DolicaAkelloEgwel** [comment]
This has been observed on the desktop too.
