### ISSUE TITLE
NaNs in result when reconstructing flower dataset with FBP_CUDA

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [mantidproject/mantidimaging#953]
### Summary

Following the example reconstruction instructions in the user guide results in some of the slices having NaNs.

### Steps To Reproduce

Use the flower dataset and follow the user guide.

### Context

Observed on IDAaaS with Mantid Imaging nightly.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/43887608/116578147-05151680-a909-11eb-9b2d-ccbacf79f9ff.png)

**Comment by samtygier-stfc** [comment]
I think this is related to this warning:

`2021-05-05 17:35:28,487 [py.warnings:L174] WARNING: /home/sam/git/mantidimaging/mantidimaging/core/reconstruct/base_recon.py:16: RuntimeWarning: invalid value encountered in log`

`return -np.log(sino)`

gives some NaN pixels for negative inputs, which then get passed to astra which returns a slice with NaNs.
